jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }} on ${{ matrix.os }}
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build --stacktrace --info
    strategy:
      matrix:
        java-version:
        - 21
        os:
        - ubuntu-latest
        - macos-latest
name: Jenetics Build
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
